### ISSUE TITLE
value cannot be null error

### ISSUE THREAD

**Issue by mattador1** [robertaachenw/solidity-debugger#17]
:36 Value cannot be null. (Parameter 'key')
15:52:36 System.NullReferenceException: Object reference not set to an instance of an object.
   at Meadow.Plugin.Builtin.Hardhat.HardhatPlugin.OnExecutionTraceAnalysis(PluginServices svc, IPatchExecutionTraceAnalysis e) in /root/sdbg/SolidityDebugger/Meadow.Plugin/Builtin/Hardhat/HardhatPlugin.cs:line 63
   at Meadow.Plugin.PluginLoader.OnExecutionTraceAnalysis(PluginServices notUsed, IPatchExecutionTraceAnalysis e) in /root/sdbg/SolidityDebugger/Meadow.Plugin/PluginLoader.cs:line 50
   
 for code, just wanted to check if approving usdt on forked mainnet works:
 
 contract DbgEntry {
    event EvmPrint(string);
    event EvmSpoofCallerOpcode(address addr);

    constructor() {
        emit EvmPrint("DbgEntry.constructor");

        IERC20 token = IERC20(0xdAC17F958D2ee523a2206206994597C13D831ec7);

        emit EvmSpoofCallerOpcode(0xc106F9A14280aCC05b0Bd083daDB6F2B896aC707);

        token.approve(
            0x42b22FaA9FC815183c0f99A28D1f8449F77A5084,
            100000000000000000000
        );

        emit EvmPrint("DbgEntry return");
    }
}

**Comment by mattador1** [comment]
seems something in my project was conflicting with this plugin (dependency compiler...), I cleaned it a little now I do not have this message any more
