### ISSUE TITLE
Unhandled exception.

### ISSUE THREAD

**Issue by memeclub** [robertaachenw/solidity-debugger#20]
Why is this happening? How to fix it?

```
C:\Users\user1\.solidity-ide\engine\SolidityDebugger.exe -P z:\Hardhat -C Test1 -B
01:50:10 # ProjectPath = z:\Hardhat

01:50:10 # SolcJsPath = C:\Users\ssryz\.solidity-ide\solc\0.8.25\solc.js

Unhandled exception. 
Newtonsoft.Json.JsonSerializationException: Could not find member 'errors' on object of type 'Doc'. Path 'contracts['@openzeppelin/contracts/access/Ownable.sol'].Ownable.devdoc.errors', line 1, position 1436.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(IDictionary dictionary, JsonReader reader, JsonDictionaryContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(IDictionary dictionary, JsonReader reader, JsonDictionaryContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject[T](JsonSerializer jsonSerializer)
   at SolcNet.DataDescription.Output.OutputDescription.FromJsonString(String jsonStr) in /root/sdbg/SolidityDebugger/SolcNet/DataDescription/Output/OutputDescription.cs:line 18
   at SolcNet.SolcLibPortable.CompileInputDescriptionJson(String jsonInput, CompileErrorHandling errorHandling, Dictionary`2 soliditySourceFileContent) in /root/sdbg/SolidityDebugger/SolcNet/SolcLibPortable.cs:line 95
   at SolcNet.SolcLibPortable.Compile(InputDescription input, CompileErrorHandling errorHandling, Dictionary`2 soliditySourceFileContent) in /root/sdbg/SolidityDebugger/SolcNet/SolcLibPortable.cs:line 117
   at Meadow.SolCodeGen.CodebaseGenerator.GenerateSources() in /root/sdbg/SolidityDebugger/SolidityDebugger/SolCodeGen/CodebaseGenerator.cs:line 220
   at Meadow.SolCodeGen.CodebaseGenerator.Generate(CommandArgs appArgs, Boolean returnFullSources, LoggerDelegate logger) in /root/sdbg/SolidityDebugger/SolidityDebugger/SolCodeGen/CodebaseGenerator.cs:line 65
   at Meadow.DebugSolSources.Program.GetSolcCompilationData(AppOptions opts) in /root/sdbg/SolidityDebugger/SolidityDebugger/Program.cs:line 194
   at Meadow.DebugSolSources.Program.Main(String[] args) in /root/sdbg/SolidityDebugger/SolidityDebugger/Program.cs:line 55
   at Meadow.DebugSolSources.Program.<Main>(String[] args)

========== Build: 0 succeeded, 1 failed, 0 skipped ==========
```

**Comment by edisonX-sudo** [comment]
the same. any one who solved this issue?

**Comment by edisonX-sudo** [comment]
@memeclub 
try 2 downgrade the solidity version to 0.8.17, openzeppelin to 4.9.6
works in my mac
