### ISSUE TITLE
Could not find member 'custom:oz-upgrades-unsafe-allow' on object of type 'Doc'.

### ISSUE THREAD

**Issue by itxtoledo** [robertaachenw/solidity-debugger#8]
```
Could not find member 'custom:oz-upgrades-unsafe-allow' on object of type 'Doc'. Path 'contracts['@openzeppelin/contracts-upgradeable/proxy/utils/Initializable.sol'].Initializable.devdoc.custom:oz-upgrades-unsafe-allow', line 1, position 6945. => Newtonsoft.Json.JsonSerializationException: Could not find member 'custom:oz-upgrades-unsafe-allow' on object of type 'Doc'. Path 'contracts['@openzeppelin/contracts-upgradeable/proxy/utils/Initializable.sol'].Initializable.devdoc.custom:oz-upgrades-unsafe-allow', line 1, position 6945.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(IDictionary dictionary, JsonReader reader, JsonDictionaryContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(IDictionary dictionary, JsonReader reader, JsonDictionaryContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject[T](JsonSerializer jsonSerializer)
   at SolcNet.DataDescription.Output.OutputDescription.FromJsonString(String jsonStr) in /root/sdbg/SolidityDebugger/SolcNet/DataDescription/Output/OutputDescription.cs:line 18
   at SolcNet.SolcLibPortable.CompileInputDescriptionJson(String jsonInput, CompileErrorHandling errorHandling, Dictionary`2 soliditySourceFileContent) in /root/sdbg/SolidityDebugger/SolcNet/SolcLibPortable.cs:line 95
   at SolcNet.SolcLibPortable.Compile(InputDescription input, CompileErrorHandling errorHandling, Dictionary`2 soliditySourceFileContent) in /root/sdbg/SolidityDebugger/SolcNet/SolcLibPortable.cs:line 117
   at Meadow.SolCodeGen.CodebaseGenerator.GenerateSources() in /root/sdbg/SolidityDebugger/SolidityDebugger/SolCodeGen/CodebaseGenerator.cs:line 220
   at Meadow.SolCodeGen.CodebaseGenerator.Generate(CommandArgs appArgs, Boolean returnFullSources, LoggerDelegate logger) in /root/sdbg/SolidityDebugger/SolidityDebugger/SolCodeGen/CodebaseGenerator.cs:line 65
   at Meadow.DebugSolSources.Program.GetSolcCompilationData(AppOptions opts) in /root/sdbg/SolidityDebugger/SolidityDebugger/Program.cs:line 194
   at Meadow.DebugSolSources.Program.Run(String[] args) in /root/sdbg/SolidityDebugger/SolidityDebugger/Program.cs:line 107
   at Meadow.DebugSolSources.Program.Main(String[] args) in /root/sdbg/SolidityDebugger/SolidityDebugger/Program.cs:line 87
```

**Comment by robertaachenw** [comment]
Could you please provide the source you compiled that generated this error?
